openapi: 3.0.3
info:
  title: TypeScript OpenAPI
  description: OpenAPIを使ってTypeScriptで書かれたAPIのドキュメントを作成作ってみる
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: local

tags:
  - name: help
    description: ヘルプ系
  - name: util
    description: 便利ツール系

paths:
  /:
    get:
      summary: Hello World
      description: 接続確認用のパス
      tags:
        - help
      responses:
        '200':
          description: アプリケーション名を返す
          content:
            text/plain:
              schema:
                type: string
                example: TypeScript OpenAPI
  /api-docs:
    get:
      summary: SwaggerAPI Docs
      description: SwaggerによるAPIの定義書
      tags:
        - help
      parameters:
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/DocsDataType'
          description: 返却するAPI Docsの型
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/yaml:
              schema:
                type: string
  /util/now:
    get:
      summary: 現在時刻
      tags:
        - util
      responses:
        '200':
          description: 様々な種類の現在時刻
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateTime'

components:
  schemas:
    DocsDataType:
      type: string
      enum:
        - json
        - yaml
    DateTime:
      type: object
      properties:
        datetime:
          type: string
          description: 現在時刻
          example: 2022/02/22 12:00:00
          format: date-fullyear "/" date-month "/" date-mday " " partial-time
        offset:
          type: string
          description: オフセット付き現在時刻
          example: 2022-01-22T12:00:00+09:00
          format: full-date "T" partial-time time-numoffset
        calender:
          type: string
          description: 日付
          example: 2022-01-22
          format: full-date
        timestamp:
          type: integer
          description: タイムスタンプ
        year:
          type: integer
          description: 年
          example: 2022
        month:
          type: integer
          description: 月
          example: 1
        date:
          type: integer
          description: 日
          example: 1
        day:
          type: string
          description: 曜日
          example: 日
        hour:
          type: integer
          description: 時（24時間制）
          example: 1
        minute:
          type: integer
          description: 分
          example: 0
        second:
          type: integer
          description: 秒
          example: 0
      required:
        - datetime
        - offset
        - calender
        - timestamp
        - year
        - month
        - date
        - day
        - hour
        - minute
        - second
