openapi: 3.0.3
info:
  title: TypeScript OpenAPI
  description: OpenAPIを使ってTypeScriptで書かれたAPIのドキュメントを作成作ってみる
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: local

tags:
  - name: help
    description: ヘルプ系

paths:
  /:
    get:
      summary: Hello World
      description: 接続確認用のパス
      tags:
        - help
      responses:
        '200':
          description: アプリケーション名を返す
          content:
            text/plain:
              schema:
                type: string
                example: TypeScript OpenAPI
  /api-docs:
    get:
      summary: SwaggerAPI Docs
      description: SwaggerによるAPIの定義書
      tags:
        - help
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum:
              - json
              - yaml
          description: 返却するAPI Docsの型
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/yaml:
              schema:
                type: string
