/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** 接続確認用のパス */
    get: {
      responses: {
        /** アプリケーション名を返す */
        200: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
  "/api-docs": {
    /** SwaggerによるAPIの定義書 */
    get: {
      parameters: {
        query: {
          /** 返却するAPI Docsの型 */
          type?: components["schemas"]["DocsDataType"];
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
            "text/yaml": string;
          };
        };
      };
    };
  };
  "/util/now": {
    get: {
      responses: {
        /** 様々な種類の現在時刻 */
        200: {
          content: {
            "application/json": components["schemas"]["DateTime"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /** @enum {string} */
    DocsDataType: "json" | "yaml";
    DateTime: {
      /**
       * Format: date-fullyear "/" date-month "/" date-mday " " partial-time
       * @description 現在時刻
       * @example 2022/02/22 12:00:00
       */
      datetime: string;
      /**
       * Format: full-date "T" partial-time time-numoffset
       * @description オフセット付き現在時刻
       * @example 2022-01-22T03:00:00.000Z
       */
      offset: string;
      /**
       * Format: full-date
       * @description 日付
       * @example 2022-01-22T00:00:00.000Z
       */
      calender: string;
      /** @description タイムスタンプ */
      timestamp: number;
      /**
       * @description 年
       * @example 2022
       */
      year: number;
      /**
       * @description 月
       * @example 1
       */
      month: number;
      /**
       * @description 日
       * @example 1
       */
      date: number;
      /**
       * @description 曜日
       * @example 日
       */
      day: string;
      /**
       * @description 時（24時間制）
       * @example 1
       */
      hour: number;
      /** @description 分 */
      minute: number;
      /** @description 秒 */
      second: number;
    };
  };
}

export interface operations {}

export interface external {}
